kind: Service
apiVersion: v1
metadata:
  labels:
    app: broken-biscuit-microservice-service
    stack: frontend
  name: broken-biscuit-microservice-service
  namespace: default
spec:
  selector:
    source: demo
    app: broken-biscuit-microservice
  ports:
    -   name: web
        protocol: TCP
        port: 30201
        targetPort: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    stack: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: broken-biscuit-ingress
  namespace: default
spec:
  rules:
    -   http:
          paths:
            -   path: /broken-biscuit(/|$)(.*)
                pathType: Prefix
                backend:
                  service:
                    name: broken-biscuit-microservice-service
                    port:
                      number: 30201
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: broken-biscuit-microservice
    stack: frontend
    source: demo
  name: broken-biscuit-microservice
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: broken-biscuit-microservice
  template:
    metadata:
      labels:
        app: broken-biscuit-microservice
        run: broken-biscuit-microservice
        source: demo
      namespace: default
    spec:
      containers:
        -   image: 219099013464.dkr.ecr.us-west-2.amazonaws.com/broken-biscuit-microservice
            name: broken-biscuit-microservice
            ports:
              -   name: web
                  containerPort: 9000
            env:
              -   name: MONGO_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: football-app-configmap
                      key: mongo_host
              -   name: MONGO_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: football-app-configmap
                      key: mongo_port
              -   name: MONGO_USERNAME
                  value: root
              -   name: MONGO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mongodb
                      key: mongodb-root-password
              -   name: DATABASE_NAME
                  value: broken-biscuit-football-app
